SGEHookah/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path
import core.views as view
import core.my_views.vendas as vendas
from django.contrib.auth import views as auth_views

urls_usuario = [
    path('', view.user_main, name="user_main"),
    path('AlterarSenha', view.change_pw_form, name="user_alterar_senha"),
    path('AlterarInfo', view.update_user_form, name="update_user_form")
]

urls_clientes = [
    path('cadastrar/', view.cadastrar_cliente, name="cadastrar_cliente"),
    path('cadastrar/cadastro_rapido/', view.cadastro_rapido_cliente,
         name="cadastro_rapido_cliente"),
    path('<int:id_cliente>/', view.editar_cliente, name="editar_cliente"),
    path('lista/', view.lista_clientes, name="lista_clientes"),
    path('deletar/<int:id_cliente>/', view.deletar_cliente, name="deletar_cliente")
]

urls_produtos = [
    path('cadastrar/', view.CadastrarProduto.as_view(), name="cadastrar_produto"),
    path('<int:id_produto>/', view.PaginaProduto.as_view(), name="product_page"),
    path('<int:id_produto>/formula/', view.formula_produto, name="formula_produto"),
    path('lista/', view.lista_produtos, name="lista_produtos"),
    path('deletar/<int:id_produto>/', view.deletar_produto, name="deletar_produto"),
    path('materia/cadastrar/', view.cadastrar_materia, name="cadastrar_materia"),
    path('materia/lista/', view.lista_materia, name="lista_materia"),
    path('materia/<int:id_materia>/', view.editar_materia, name="editar_materia"),
    path('materia/deletar/<int:id_materia>', view.deletar_materia, name="deletar_materia"),
    path('categorias/', view.lista_categorias, name="lista_categorias"),
    path('categorias/deletar/<int:id_categoria>/',
         view.deletar_categoria, name="deletar_categoria"),
    path('categorias/<int:id_categoria>/', view.editar_categoria, name="editar_categoria"),
    path('unidades/', view.lista_unidades, name="lista_unidades"),
    path('unidades/deletar/<int:id_unidade>/',
         view.deletar_unidade, name="deletar_unidade"),
    path('unidades/<int:id_unidade>/', view.editar_unidade, name="editar_unidade")
]

urls_producao = [
    path('formulas/lista/', view.lista_formula, name="lista_formulas"),
    path('formulas/deletar/<int:id_formula>',
         view.deletar_formula, name="deletar_formula"),
    path('formulas/<int:id_formula>/', view.pagina_formula, name="pagina_formula"),
    path('pedidos/', view.lista_fabricacao, name="lista_fabricacao"),
    path('pedidos/novo/', view.nova_fabricacao, name="nova_fabricacao"),
    path('pedidos/<int:id_fabricacao>/',
         view.editar_fabricacao, name="editar_fabricacao"),
    path('pedidos/deletar/<int:id_fabricacao>', view.deletar_fabricacao, name="deletar_fabricacao")
]

urls_vendas = [
    path('', vendas.ListaVendas.as_view(), name="lista_vendas"),
    path('nova/', vendas.NovaVenda.as_view(), name="nova_venda"),
    path('deletar/<int:id_venda>', vendas.DeletarVenda.as_view(), name="deletar_venda"),
]

urls_fornecedores = [
    path('cadastrar/', view.cadastrar_fornecedor, name="cadastrar_fornecedor"),
    path('lista/', view.lista_fornecedores, name="lista_fornecedores"),
    path('deletar/<int:id_fornecedor>/', view.deletar_fornecedor, name="deletar_fornecedor"),
    path('<int:id_fornecedor>/', view.editar_fornecedor, name="editar_fornecedor"),
]

api = [
    path('valida_fabricacao/<int:id_formula>', view.valida_fabricacao, name="valida_fabricacao"),
    path('get_produto/', view.get_produto, name="get_produto"),
    path('search_produto/', view.search_produto, name="search_produto"),
]

urlpatterns = [
    path('admindjango/', admin.site.urls),
    path('admin/', auth_views.LoginView.as_view(template_name='index.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page="/")),
    path('admin/home/', view.home, name="home"),
    path('', view.redirect_home),
    path('iframe/home/', view.iframe_home, name="iframe_home"),
    path('iframe/produtos/', include(urls_produtos)),
    path('admin/usuario/', include(urls_usuario)),
	path('iframe/fornecedores/', include(urls_fornecedores)),
    path('iframe/clientes/', include(urls_clientes)),
    path('iframe/producao/', include(urls_producao)),
    path('iframe/vendas/', include(urls_vendas)),
    path('iframe/vendas/calcula_frete/', view.calcula_frete, name="calcula_frete"),

    path('api/', include(api)),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/forms.py
"""
    Módulo que contem fórmularios utilizados no sistema
"""
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime as dt
import localflavor.br.forms as lf

from django.forms.models import modelformset_factory
from django.forms.models import BaseModelFormSet
from django import forms
from django.contrib.auth.models import User

import core.models as model


class CategoriaprodutoForm(forms.ModelForm):
    """ Formulário de Categoria de Produto """

    nomecategoria = forms.CharField(label="Nome da Categoria", max_length=50)

    nomecategoria.widget.attrs.update({'placeholder': '...'})

    class Meta:
        model = model.Categoriaproduto
        fields = ["nomecategoria"]


class UnidademedidaForm(forms.ModelForm):
    """ Fórmulário de Unidade de Medida """

    unidademedida = forms.CharField(label="Unidade", max_length=50)

    unidademedida.widget.attrs.update({'placeholder': '...'})

    class Meta:
        model = model.Unidademedida
        fields = ["unidademedida"]


class CadProdutoForm(forms.ModelForm):
    """ Formulário para cadastrar um produto """

    codproduto = forms.CharField(label="Código", max_length=8)
    nomeproduto = forms.CharField(label="Nome", max_length=50)
    preco = forms.DecimalField(label="Preço", max_digits=10, decimal_places=2)
    precocusto = forms.DecimalField(
        label="Preço de Custo", max_digits=10, decimal_places=2, required=False)
    sabor = forms.CharField(label="Sabor", max_length=45)
    marca = forms.CharField(label="Marca", required=False)
    altura = forms.FloatField(label="Altura (cm)")
    largura = forms.FloatField(label="Largura (cm)")
    profundidade = forms.FloatField(label="Profundidade (cm)")
    peso = forms.DecimalField(
        max_digits=10, decimal_places=3, label="Peso (Kg)")
    fkid_categoria = forms.ModelChoiceField(
        label="Categoria", queryset=model.Categoriaproduto.objects.filter(hide=False), initial=0)
    fkid_unidademedida = forms.ModelChoiceField(
        label="Unidade", queryset=model.Unidademedida.objects.filter(hide=False), initial=0)
    fotoproduto = forms.FileField(label="Escolha a Foto", required=False)
    descricao = forms.CharField(
        label="Descrição", widget=forms.Textarea, required=False)

    fotoproduto.widget.attrs.update({'class': 'FotoInput'})

    class Meta:
        model = model.Produto
        fields = ["codproduto", "preco", "sabor", "altura", "profundidade", "fkid_unidademedida",
                  "nomeproduto", "precocusto", "marca", "largura", "peso", "fkid_categoria",
                  "fotoproduto", "descricao"]


class ProdutoForm(forms.ModelForm):
    """ Formulário para editar um produto """

    codproduto = forms.CharField(label="Código", max_length=8)
    nomeproduto = forms.CharField(label="Nome")
    preco = forms.DecimalField(label="Preço", max_digits=10, decimal_places=2)
    precocusto = forms.DecimalField(
        label="Preço de Custo", max_digits=10, decimal_places=2, required=False)
    sabor = forms.CharField(label="Sabor")
    marca = forms.CharField(label="Marca", required=False)
    altura = forms.FloatField(label="Altura")
    largura = forms.FloatField(label="Largura")
    profundidade = forms.FloatField(label="Profundidade")
    peso = forms.DecimalField(max_digits=10, decimal_places=3, label="Peso")
    fkid_categoria = forms.ModelChoiceField(
        label="Categoria", queryset=model.Categoriaproduto.objects.filter(hide=False), initial=0)
    fkid_unidademedida = forms.ModelChoiceField(
        label="Unidade", queryset=model.Unidademedida.objects.filter(hide=False), initial=0)
    totalestoque = forms.FloatField(label="Estoque")
    fotoproduto = forms.FileField(label="Escolha a Foto", required=False)
    descricao = forms.CharField(
        label="Descrição", widget=forms.Textarea, required=False)

    descricao.widget.attrs.update({'class': 'Descricao'})
    fotoproduto.widget.attrs.update({'class': 'FotoInput'})
    altura.widget.attrs.update({'placeholder': 'Em cm'})
    largura.widget.attrs.update({'placeholder': 'Em cm'})
    profundidade.widget.attrs.update({'placeholder': 'Em cm'})
    peso.widget.attrs.update({'placeholder': 'Em kg'})

    class Meta:
        model = model.Produto
        fields = [
            "codproduto", "nomeproduto", "preco",
            "precocusto", "sabor", "marca",
            "altura", "largura", "profundidade",
            "peso", "fkid_unidademedida", "fkid_categoria",
            "totalestoque", "fotoproduto", "descricao"
        ]


class FormulaprodutoForm(forms.ModelForm):
    """ Formulário de fórmula de produto para página do produto """

    tempomaturacao = forms.TimeField(
        label="Tempo em Maturação", initial='00:00:00')

    class Meta:
        model = model.Formulaproduto
        fields = ["tempomaturacao"]


class FormulaCompletaForm(forms.ModelForm):
    """ Formulário de fórmula para página individual da formula """

    tempomaturacao = forms.TimeField(
        label="Tempo em Maturação", initial='00:00:00')
    fkid_produto = forms.ModelChoiceField(
        label="Produto", queryset=model.Produto.objects.filter(hide=False))

    class Meta:
        model = model.Formulaproduto
        fields = ["tempomaturacao", "fkid_produto"]


class FormulamateriaForm(forms.ModelForm):
    """ Formulário para linha de matéria prima de uma Fórmula """

    fkid_materiaprima = forms.ModelChoiceField(
        label="Matéria Prima",
        queryset=model.Materiaprima.objects.filter(hide=False),
        required=True)
    quantidade = forms.FloatField(label="Quantidade", required=True)
    unidade = forms.ModelChoiceField(
        label="Unidade",
        queryset=model.Unidademedida.objects.filter(hide=False), required=True)

    class Meta:
        model = model.Formulamateria
        fields = ["fkid_materiaprima", "quantidade", "unidade"]


class MateriaPrimaForm(forms.ModelForm):
    """ Formulário para matéria-prima """

    materiaprima = forms.CharField(label="Matéria Prima", max_length=60)
    marca = forms.CharField(label="Marca", max_length=50, required=False)
    totalestoque = forms.IntegerField(label="Estoque")
    unidade = forms.ModelChoiceField(
        label="Unidade", queryset=model.Unidademedida.objects.filter(hide=False), initial=0)

    class Meta:
        model = model.Materiaprima
        fields = ["materiaprima", "marca", "totalestoque", "unidade"]


class FreteForm(forms.Form):
    """ Formulário para calcular frete """

    tipo_choices = (('4014', 'Sedex'), ('4510', 'PAC'))
    nCdServico = forms.CharField(
        label="Serviço", widget=forms.Select(choices=tipo_choices))
    formato_choices = ((1, "Caixa"), (2, "Rolo/Prisma"), (3, "Envelope"))
    nCdFormato = forms.IntegerField(
        label="Formato", widget=forms.Select(choices=formato_choices))
    sCepOrigem = forms.IntegerField(
        label="Cep Origem", widget=forms.NumberInput(attrs={'placeholder': '0000000'}))
    sCepDestino = forms.IntegerField(
        label="Cep Destino", widget=forms.NumberInput(attrs={'placeholder': '0000000'}))
    nVlPeso = forms.FloatField(label="Peso", widget=forms.NumberInput(
        attrs={'placeholder': 'Peso em Kg'}))
    nVlLargura = forms.FloatField(label="Largura", widget=forms.NumberInput(
        attrs={'placeholder': 'Largura em cm'}))
    nVlComprimento = forms.FloatField(label="Comprimento", widget=forms.NumberInput(
        attrs={'placeholder': 'Comprimento em cm'}))
    nVlAltura = forms.FloatField(label="Altura", widget=forms.NumberInput(
        attrs={'placeholder': 'Altura em cm'}))
    #nVlDiametro = forms.FloatField(label="Diametro")
    # sCdMaoPropria
    # nVlValorDeclarado
    # sCdAvisoRecebimento


class UpdateInfoForm(forms.ModelForm):
    """ Formulário para atualizar informações de um usuário """

    email = forms.EmailField(label="E-mail", required=True)
    first_name = forms.CharField(label="Nome", required=True)
    last_name = forms.CharField(label="Sobrenome", required=True)

    class Meta:
        model = model.User
        fields = ('email', 'first_name', 'last_name')

    def clean_email(self):
        """ Confirma se o email já existe no banco de dados """

        email = self.cleaned_data.get('email')
        if email and User.objects.filter(email=email).count():
            raise forms.ValidationError('Esse e-mail já está em uso.')
        return email

    def save(self, commit=True):
        user = super(UpdateInfoForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EnderecoForm(forms.ModelForm):
    """ Formulário de endereço """

    cep = forms.CharField(label="CEP", max_length=9)
    logradouro = forms.CharField(label="Endereço", max_length=200)
    endereco_numero = forms.IntegerField(label="Número", required=False)
    complemento = forms.CharField(
        label="Complemento", max_length=20, required=False)
    bairro = forms.CharField(label="Bairro", max_length=100)
    cidade = forms.CharField(label="Cidade", max_length=150)
    uf = lf.BRStateChoiceField(label="UF")

    class Meta:
        model = model.Endereco
        fields = [
            'cep', 'logradouro', 'endereco_numero',
            'complemento', 'bairro', 'cidade',
            'uf'
        ]


class TelefoneForm(forms.ModelForm):
    """ Formulário para Telefone """

    numero = forms.CharField(label='Telefone', max_length=15, required=False)

    class Meta:
        model = model.Telefone
        fields = ['numero']


class PessoaForm(forms.ModelForm):
    """ Formulário para cadastro de uma nova pessoa """

    genero_choices = (('H', 'Homem'), ('M', 'Mulher'), ('O', 'Outro'))

    nomecompleto_razaosocial = forms.CharField(label="Nome", max_length=150)
    apelido_nomefantasia = forms.CharField(
        label="Apelido", required=False, max_length=150)

core/views.py
"""
    Contém as views principais do sistema
    as views especificas estão na pasta my_views e custom
    Também é utilizado os arquivos funcoes.py
"""

from django.shortcuts import render, redirect

import core.forms as forms
import core.models as model

from core.funcoes import *
from core.my_views.clientes import *
from core.my_views.produtos import *
from core.my_views.usuario import *
from core.my_views.producao import *
from core.my_views.fornecedores import *
from core.api.api import *

# Create your views here.


def index(request):
    """ Retorna a página inicial (Login) """

    return render(request, "index.html")

# Home e Principais


@login_required(login_url="/admin")
def home(request):
    """ Página Principal do sistema
        Segura o iframe
    """
    
    statusVendas = [
        stat.descricao for stat in models.Statusvenda.objects
        .all()
        .order_by('order')
    ]
    print(statusVendas)

    context = {
        "statusVendas":statusVendas,
    }

    return render(request, "base.html", context)


@login_required(login_url="/admin")
def redirect_home(request):
    """ Redirect para a Página Inicial """
    return redirect('/admin/home')


@login_required(login_url="/admin")
def iframe_home(request):
    """ Página inicial no iframe """

    # Info sobre pedidos de fabricação
    pedidosFabricacao = models.Pedidofabricacao.objects.filter(
        hide=False
    ).exclude(
        fkid_statusfabricacao__order=3
    ).order_by(
        '-fkid_statusfabricacao', 'dt_fim_maturacao'
    )

    context = {
        "fabricacaoPiece":"iframe/pieces/fabricacaoDetail.html",
        "pedidosFabricacao":pedidosFabricacao
    }
    return render(request, "iframe/home.html", context)

# Frete


@login_required(login_url="/admin")
def calcula_frete(request):
    """ Sem uso no momento """

    retorno = {"Valor": "0,00", "PrazoEntrega": 0, "MsgErro": "None"}
    if request.POST:
        form = forms.FreteForm(request.POST)
        if form.is_valid():
            # Arruma os campos de altura, comprimento e largura para não dar erro.
            if form.cleaned_data['nVlAltura'] < 2:
                form.cleaned_data['nVlAltura'] = 2
            if form.cleaned_data['nVlComprimento'] < 16:
                form.cleaned_data['nVlComprimento'] = 16
            if form.cleaned_data['nVlLargura'] < 11:
                form.cleaned_data['nVlLargura'] = 11

            try:
                retorno = calcula_frete(
                    form.cleaned_data['nCdServico'],
                    form.cleaned_data['sCepOrigem'],
                    form.cleaned_data['sCepDestino'],
                    form.cleaned_data['nVlPeso'],
                    form.cleaned_data['nCdFormato'],
                    form.cleaned_data['nVlComprimento'],
                    form.cleaned_data['nVlAltura'],
                    form.cleaned_data['nVlLargura']
                )
            except:
                print("Você está sem internet")
    else:
        form = forms.FreteForm()
    context = {
        "form": form,
        "Valor": retorno.get('Valor'),
        "PrazoEntrega": retorno.get('PrazoEntrega'),
        "MsgErro": retorno.get('MsgErro')
    }
    return render(request, "iframe/vendas/calcula_frete.html", context)

core/templates/iframe/produtos/cadastrar_produto.html
<html>
<head>
	<title id="iframe_title">SGE - Cadastrar Produto</title>

	<link rel="stylesheet"  type="text/css" href="/static/css/site.css"/>
    
    <link rel="stylesheet"  type="text/css" href="/static/css/patterns/cadastro.css"/>
    <link rel="stylesheet"  type="text/css" href="/static/css/iframe/produtos/cadastrar_produto.css"/>

	<script src="/static/jquery/jquery-3.3.1.min.js"></script>
    <script src="/static/jquery/jquery.mask.min.js"></script>

    <script src="/static/jquery/jquery-3.3.1.min.js"></script>
	<script src="/static/js/utils.js"></script>
</head>

<body>
	
	
	{% if success == 'True' %}
	<div class="overlay" id="overlay">
		<div class="overlay_bg">
		</div>
		
		<div class="overlay_content">
			<h2 class="overlay_title">PRODUTO CADASTRADO COM SUCESSO</h2>
			
			<div class="bt_wrapper">
				<a href="{% url 'cadastrar_produto' %}"><button class="btMain btConfirmar">Continuar</button></a>
			</div>
			
		</div>
	</div>
	{% endif %}
	
	<section class="content">
		<div>
			<form method="POST" enctype="multipart/form-data" autocomplete="off">
				<h2>Cadastrar Produto</h2>
				<div class="formInputContainer">
				{% csrf_token %}

					<div class="columns_holder">

						<div class="col">
						
							{% for field in form_col1 %}

							<div class="fieldDiv">
								<div class="formInput">
									<div class="label">{{field.label_tag}}</div>
									<div class="input">{{field}}
										{{field.errors}}
									</div>
								</div>
							</div>

							{% endfor %}

						</div>

						<div class="col">

							{% for field in form_col2 %}

							<div class="fieldDiv">
								<div class="formInput">
									<div class="label">{{field.label_tag}}</div>
									<div class="input">{{field}}
										{{field.errors}}
									</div>
								</div>
							</div>

							{% endfor %}

						</div>

					</div>

					<div class="fotoDiv">
						<div class="formInput vertical">
							<div class="label_ft" id="label_ft_div">{{form.fotoproduto.label_tag}}</div>
							<div class="input_ft">{{form.fotoproduto}}
									{{form.fotoproduto.errors}}
							</div>
						</div>
						<div class="div_foto_preview" id="div_foto_preview">
							<img class="img_foto_preview" id="foto_preview"/>
						</div>
					</div>

					<div class="fieldDiv">
						<div class="formInput">
							<div class="label">{{form.descricao.label_tag}}</div>
							<div class="input">{{form.descricao}}
								{{form.descricao.errors}}
							</div>
						</div>
					</div>

				</div>

				<div class="botaoContainer">
					<button class="btMain btCancelar" type="reset">Limpar</button>
					<button class="btMain btConfirmar" type="submit">Cadastrar</button>
				</div>

				</div>
			</form>
		</div>
	</section>

<script src="/static/js/iframe/produtos/cadastrar_produto.js"></script>
<script src="/static/js/formsFixes.js"></script>

</body>
</html>

core/templates/iframe/produtos/formula_produto.html
<html>
<head>
	<title id="iframe_title">SGE - Fórmula Produto</title>

	<link rel="stylesheet"  type="text/css" href="/static/css/site.css"/>
    
    <link rel="stylesheet"  type="text/css" href="/static/css/patterns/cadastro.css"/>
    <link rel="stylesheet"  type="text/css" href="/static/css/my_css/formset_manager.css"/>

    <script src="/static/jquery/jquery-3.3.1.min.js"></script>
	<script src="/static/jquery/jquery.mask.min.js"></script>
	
	<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.css" rel="stylesheet" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.full.js"></script>

	<script src="/static/js/utils.js"></script>
</head>

<body>
	
	
	{% if success == 'True' %}
	<div class="overlay" id="overlay">
		<div class="overlay_bg">
		</div>
		
		<div class="overlay_content">
			<h2 class="overlay_title">FÓRMULA SALVA COM SUCESSO</h2>
			
			<div class="bt_wrapper">
				<a href="/iframe/produtos/{{ produto.pkid_produto }}/formula"><button class="btMain btConfirmar">Continuar</button></a>
			</div>
			
		</div>
	</div>
	{% endif %}
	
	<section class="content">
			<form method="POST" autocomplete="off">
				{% csrf_token %}

					<h2 class="txt_center">{{ produto.nomeproduto }}</h2>
					<div class="flex_row_nw row_center">
					
						{% for field in form_formula %}

						<div class="fieldDiv">
							<div class="formInput">
								<div class="label">{{field.label_tag}}</div>
								<div class="input">{{field}}
									{{field.errors}}
								</div>
							</div>
						</div>

						{% endfor %}

					</div>

					<table>
						<thead>
							<tr>
								<th>Matéria Prima</th>
								<th>Quantidade</th>
								<th>Unidade</th>
								<th>Excluir</th>
							</tr>
						</thead>
						<tbody>
						{{ forms_materia.management_form }}
						{% for form in forms_materia %}
							<tr class="form-row">
								{% for field in form.hidden_fields %}
									<td class="hidden">
										{{ field }}
									</td>
								{% endfor %}
								{% for field in form.visible_fields %}
									<td class="row_center">
										{{field}}
										{{field.errors}}
									</td>
								{% endfor %}
							</tr>
						{% endfor %}
							<tr class="add_row">
								<td></td>
								<td></td>
								<td></td>
								<td class="row_center">
									<div title="nova linha-" class="opt_bt opt_add add-form-row">
									</div>
								</td>
							</tr>
						</tbody>
					</table>

					<div class="botaoContainer">
						<button class="btMain btCancelar" type="reset">Limpar</button>
						<button class="btMain btConfirmar" type="submit">Salvar</button>
					</div>

			</form>
	</section>

<script src="/static/js/iframe/produtos/cadastrar_produto.js"></script>
<script src="/static/js/formsFixes.js"></script>
<script src="/static/js/formsetManager.js"></script>

</body>
</html>

core/templates/iframe/produtos/pagina_produto.html
<html>

<head>
	<title id="iframe_title">SGE - Página Produto</title>

	<link rel="stylesheet"  type="text/css" href="/static/css/site.css"/>
	<link rel="stylesheet"  type="text/css" href="/static/css/patterns/cadastro.css"/>
	<link rel="stylesheet"  type="text/css" href="/static/css/iframe/produtos/pagina_produto.css"/>

	<script src="/static/jquery/jquery-3.3.1.min.js"></script>
	<script src="/static/jquery/jquery.mask.min.js"></script>
	
	<script src="/static/js/utils.js"></script>
</head>

<body>

	{% if success == 'True' %}
	<div class="overlay" id="overlay">
		<div class="overlay_bg">
		</div>

		<div class="overlay_content">
			<h2 class="overlay_title">PRODUTO SALVO COM SUCESSO</h2>

			<div class="bt_wrapper">
				<a href="{% url 'product_page' produto.pkid_produto %}"><button class="btMain btConfirmar">Continuar</button></a>
			</div>

		</div>
	</div>
	{% endif %}

	<section class="content">
		<form method="POST" enctype="multipart/form-data" autocomplete="OFF">
		
			{% csrf_token %}
			
			<div class="page_content">

				<div class="foto_produto">
					<img id="foto_produto" class="foto_produto" alt="{{ produto.nomeproduto }}" src="{{ produto.fotoproduto.url }}"/>		
					<img style="display:none" id="foto_preview" class="foto_produto"/>
				</div>
				
				<label class="label_fotoproduto" for="id_fotoproduto"><div class="foto_label vertical">Alterar Foto</div></label>
				<input type="file" style="display:none" name="fotoproduto" class="FotoInput" id="id_fotoproduto">

					{% for field in form_page %}	
					<div class="fieldDiv">
						<div class="formInput">
							<div class="label">{{ field.label_tag }}</div>
							<div class="input">{{ field }}
								{{ field.errors }}
							</div>
						</div>
					</div>
					{% endfor %}
					
					<div class="fieldDiv">
						<div class="formInput">
							<div class="label">{{ form.descricao.label_tag }}</div>
							<div class="input">{{ form.descricao }}
								{{ field.errors }}
							</div>
						</div>
					</div>
				
				<div class="botaoContainer">
					<button class="BtMain BtCancelar" id="BtClean" type="reset">Limpar</button>
					<button class="BtMain BtConfirmar" type="submit">Salvar</button>
				</div>
			</div>
		</form>
	</section>

<script src="/static/js/iframe/produtos/pagina_produto.js"></script>
<script src="/static/js/formsFixes.js"></script>
	
</body>

</html>